### ISSUE TITLE
Upgrade Habitica API from version 2 -> 3

### ISSUE THREAD

**Issue by crookedneighbor** [notionparallax/blog#7]
Loved your post about Habitica.

Just an FYI, the version 2 of the Habitica API will be officially [deactivated on July 15th](http://devs.habitica.com/api-v2-deprecation-notice/). 

[Here is a migration guide](http://devs.habitica.com/api-v2-v3-migration-guide/) for upgrading to version 3. If you have any questions, feel free to reach out on [Github](https://github.com/HabitRPG/habitrpg/issues) or the [Aspiring Comrades Guild](https://habitica.com/#/options/groups/guilds/2ff9822b-27f2-4774-98da-db349b57a38e).

**Comment by notionparallax** [comment]
So for the example in my post, the old URL was:

`https://habitica.com/api/v2/user/tasks/read20minutes/up`

and the new one is:

`https://habitica.com/api/v3/tasks/ab7e197f-c669-472e-8666-0e4f81c1392e/score/up`

That's a bit less friendly for non-nerds as the process to get the task ID requires a step via GETting from `https://habitica.com/api/v3/tasks/user` and then searching the JSON.

@crookedneighbor am I missing something or is this the new way? I just wanted to confirm before I rewrote the post.

**Comment by crookedneighbor** [comment]
As of right now, that is correct. I've just submitted a pull request that allows people to use a short name: https://github.com/HabitRPG/habitrpg/pull/7638

But we haven't fully committed to this yet.

If that doesn't pan out, I'm going to expose the task id on the front end.

**Comment by notionparallax** [comment]
That's awesome, thanks for confirming

**Comment by Alys** [comment]
@notionparallax You can also find task IDs through the Data Display Tool in the Data menu. Go to the "Task Overview" section and use the "toggle developer data" link that's above the top right corner of the table. If you're already using the Data Display Tool, that might be more convenient.
